"""01_initial-db

Revision ID: 0523501f6f7e
Revises: 
Create Date: 2023-03-11 18:45:57.778811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0523501f6f7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('btc_trade_time', sa.DateTime(), nullable=False),
    sa.Column('btc_price', sa.Float(), nullable=False),
    sa.Column('eth_trade_time', sa.DateTime(), nullable=False),
    sa.Column('eth_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_btc_trade_time'), 'prices', ['btc_trade_time'], unique=False)
    op.create_index(op.f('ix_prices_eth_trade_time'), 'prices', ['eth_trade_time'], unique=False)
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_eth_trade_time'), table_name='prices')
    op.drop_index(op.f('ix_prices_btc_trade_time'), table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
